---
apiVersion: v1
kind: Namespace
metadata:
  name: production
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: apisix
  labels:
    istio-injection: enabled
    
# ---

# apiVersion: v1
# kind: Namespace
# metadata:
#   name: metallb-system


