apiVersion: apisix.apache.org/v2
kind: ApisixTls
metadata:
  name: tls-local-rachakonda-me
  namespace: apisix
spec:
  hosts:
    - local.rachakonda.me
  secret:
    name: apisix-cert
    namespace: apisix
